#!/bin/sh
set -e

case "$1" in
remove|upgrade|deconfigure)
    if systemctl is-active --quiet protek.service; then
        systemctl stop protek.service || true
    fi
    ;;
*) ;;
esac

#DEBHELPER#
exit 0
